language: java
script: gradle dist

env:
  global:
  - LD_LIBRARY_PATH='/home/travis/build/ndw/xmlcalabash1/lib/AH
  - secure: g27RcVSujgAB0vwOvuQs2LPbuukck0xXQCkib2IJKrYfGpl6kDWMsOabjGj31A/nzrhRSPVG4Xyj2CScBtasvvvI6HjWxLHwKydnXUn1eouRN9SlHvY+/eewAVnBQOFVLKHUfOxhL213C4x0S2rCYZ12oeJ6Z9j7XRXjoLLmeR0=
  - secure: epDgr7lHHIkV7kN+XlXTqlP45hxia2qmom4UV6PxCJOmQE0XsB6b6KU3ErXq8mUobn7SEvpQSTk+Kp1/sJrZPbSaWhEiswRBpDTXP7quSQfcKr8Je2uELqXomz16NSL1AR1Dp8h5qyDpZPV4BwzoyVzb4gJ+GdINg4dOE0dhCi0=
  - secure: BMlH6Yko0wWhavp5vslnieHoT/1N0IvP1llgkOROfVDb3vGEZ33uzDHzjkTl6jCF1pb47A3jJtxUPM6JdrYuKZQnB2IrIBJhZkDEHITzzK6INVtAFAb8s7AYk7tiA//qBf6o8u3sEE66/XwDwTOtZYU19HfF3h2X7V3lwOTAalQ=

before_script:
  - echo whereami
  - echo `pwd`

before_install: lib/update-lib.sh

deploy:
  provider: releases
  api_key:
    secure: l3nyoZ4HIm0prCduEECCMGrQYiyom8NIuXix81qJAAhC6/M4TaiXVoWc5fmWjyCt9Z73fD0khVZjQABabwg96+tX3nEdr3zZMGmT8BgV/GWa7xFn1o7qZtv0wgwjwlo+rOWqAVEAwLxBh9p//FCNRrv5MAqKpQTtGVFMGVdwKeY=
  file:
    - build/distributions/xmlcalabash-$TRAVIS_TAG.jar
    - build/distributions/xmlcalabash-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
